[mypy]
python_version = 3.11
warn_unused_ignores = True
pretty = True

# Be strict in our code, but allow 3rd-party gaps
disallow_untyped_defs = True
no_implicit_optional = True

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-pyarrow.parquet.*]
ignore_missing_imports = True

# Tests can be looser
[mypy-tests.*]
disallow_untyped_defs = False
